name: commit workflow

on:
  push:
    branches: [feature-branch-1]

jobs:
  build:
    name: Build Maven
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        mvn clean package install
        pwd
        ls -l  
    - name: Salvando artefato
      uses: actions/upload-artifact@v3
      with:
          name: verademo.war
          path: target/verademo.war
  
  Veracode_Pipeline_Scan:
    name: Veracode Pipeline Scan
    runs-on: ubuntu-latest
    needs: [build]
    container:
      image: veracode/pipeline-scan:latest
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - name: get archive
        uses: actions/download-artifact@v3
        with:
          name: verademo.war
          path: /tmp
      - name: Veracode Pipeline Scan
        run: |
          java -jar /opt/veracode/pipeline-scan.jar \
              -vid ${{ secrets.VID }}   \
              -vkey ${{ secrets.VKEY }} \
              --file /tmp/verademo.war \
              --fail_on_severity="VeryHigh, High" \
              -jf results.json \
              -fjf filtered_results.json
        continue-on-error: true
      - name: Save Pipeline Scan filtered results
        uses: actions/upload-artifact@v3
        with:
          name: filtered_results
          path: filtered_results.json
      - name: Save Pipeline Scan standard results
        uses: actions/upload-artifact@v3
        with:
          name: Standard Pipeline Scan results
          path: results.json

  Veracode_Software_Composition_Analisys:
    runs-on: ubuntu-latest
    name: Veracode SCA Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run SCA Scan
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: |
          export SRCCLR_SCM_URI="https://github.com/lucasferreiram3/verademo-java-web.git"
          export SRCCLR_SCM_REF=${{ github.workflow }}
          export SRCCLR_SCM_REF_TYPE="branch"
          export SRCCLR_SCM_REV=${{ github.run_id }}
          
          export EXTRA_ARGS='--update-advisor --uri-as-name'
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan $EXTRA_ARGS

