name: feature branch workflow

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    name: Build Maven
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        mvn clean package install
        pwd
        ls -l  
    - name: Salvando artefato
      uses: actions/upload-artifact@v3
      with:
          name: verademo.war
          path: target/verademo.war
  
  Veracode_Sandbox_Scan:
    name: Veracode Sandbox Scan
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: get archive
        uses: actions/download-artifact@v3
        with:
          name: verademo.war
          path: .
      - name: Veracode Sandbox Scan
        uses: veracode/veracode-uploadandscan-action@0.2.4
        with:
          appname: 'Java-VeraDemo'
          createprofile: false
          filepath: 'target/verademo.war'
          vid: '${{ secrets.VID }}'
          vkey: '${{ secrets.VKEY }}'
          createsandbox: false
          sandboxname: '${{ github.ref }}'
          deleteincompletescan: 2
          scantimeout: 15

  Veracode_Software_Composition_Analisys:
    runs-on: ubuntu-latest
    name: Veracode SCA Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run SCA Scan
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: |
          export SRCCLR_SCM_URI="https://github.com/lucasferreiram3/verademo-java-web.git"
          export SRCCLR_SCM_REF=${{ github.workflow }}
          export SRCCLR_SCM_REF_TYPE="branch"
          export SRCCLR_SCM_REV=${{ github.run_id }}
          
          export EXTRA_ARGS='--update-advisor --uri-as-name'
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan $EXTRA_ARGS